### ISSUE TITLE
Examples are not extracted from path operations

### ISSUE THREAD

**Issue by recmanj** [Endava/cats#157]
I've got an OpenAPI spec that defines the parameter examples under path operations like in [Adding Examples
](https://swagger.io/docs/specification/v3_0/adding-examples/):
```
parameters:
  - in: query
    name: status
    schema:
      type: string
      enum: [approved, pending, closed, new]
      example: approved # Example of a parameter value
```
This gets completely ignored even when using `--useExamples` argument and random values get generated instead. Is this expected behaviour? Would it be possible to implement extracting these kind of examples?

Thanks.
