### ISSUE TITLE
Incorrect generation of enum arrays

### ISSUE THREAD

**Issue by unrealwork** [Endava/cats#163]
Incorrect generation of enum arrays 

**To Reproduce**

1. Declare some enum
```yaml
 PaymentMethod:
  type: string
  description: Payment method name
  enum: ['PAYMENT_CARD', 'PAYMENT_CARD_BINDING', 'APPLE_PAY', 'GOOGLE_PAY', 'BANK_ACCOUNT', 'CLICK_TO_PAY']
```
2. Declare property which represents an array of such enums 
```yaml
availablePaymentMethods:
  type: array
  items:
    $ref: '#/components/schemas/PaymentMethod'
```
3. Try to fuzz test API operation which has  such array property in the request body
4. In the generated payload in a test, the following data is generated for such fields
```json
[
    {
        "availablePaymentMethods": "PAYMENT_CARD"
    },
    {
        "availablePaymentMethods": "PAYMENT_CARD"
    }
]
```

**Expected behavior**
Generated data should be an array of string
```json
["PAYMENT_CARD", "PAYMENT_CARD"]
```

**Environment:**
> cats-13.1.1, build time 2025-03-05T06:37:09Z UTC, platform Linux-5.15.167.4-microsoft-standard-WSL2-amd64
