### ISSUE TITLE
CATS fails on HTTP GET with query parameters

### ISSUE THREAD

**Issue by sin-bin** [Endava/cats#2]
CATS will replace url path parameters. However, query parameters are not set or replaced. For example:
`http://localhost/api/{id}?sortBy={sortProperty}`

Query parameter "`sortBy`" is not set in the Full Request Path.

OpenAPI swagger fully supports query parameters:

```
     parameters:
        - in: query
          name: sortBy
          schema:
            type: string
```
