### ISSUE TITLE
How to add mine dictionaries?

### ISSUE THREAD

**Issue by comat0zz** [Endava/cats#26]
In CustomFuzzer there are examples of how to specify the path and fields, but what if I need the fuzzer to go through all the paths and fields in swagger file. Can you give an example? Or how to add your own payloads dictionary for substitution in the fields? For example, on all lines or numbers?

**Comment by en-milie** [comment]
Hi @comat0zz. The `CustomFuzzer` is only intended to create functional tests without writing actual code. More like a DSL where you can instruct CATS to run specific tests for specific paths with specific values and let CATS fill in the gaps. You can verify results and use variables across tests. As I said, typical to a functional test.

If you want to pass your own values within specific fields you can use the `--refData` argument where you pass a file with a syntax described in the README file. You can use `all` if the value is supplied for all paths. Or specify the exact path if that values only applies for a specific path.

**Comment by comat0zz** [comment]
Hi @en-milie !
Not quite the answer I was expecting. ^)

I want to make one dictionary for all fields of a certain type. For instance:
1. for all string value - this is a check for sql injection.
2. for all numbers  value - large numbers, marginal values.


How should it look like? Let's look at an example of a **Security Fuzzer**. How can I modify it? 

```
/pet:
    test_1:
      description: Run XSS scenarios
      name: "My Pet"
      expectedResponseCode: 200
      targetFields:
        - pet#id
        - pet#description
      stringsFile: xss.txt
```

**/pet** change to **all**? 
**targetFields: - pet#id** change to ... ? **all#all** ? empty? 

how to set the required type of dictionary for a certain type of fields?
