### ISSUE TITLE
String values are sent as integer values

### ISSUE THREAD

**Issue by VytautasKz** [Endava/cats#74]
Hello,

With CATS version 9.0.0, I've observed that when the API spec has a value defined as a string with an example set to a numerical character, and the Security fuzzer file has the value set to a value of 1 enclosed in quotation marks, the fuzzer, rather than sending a string value enclosed in quotation marks, sends an integer value with no quotation marks.

Offending API specification snippet:

```yaml
       requestBody:
         content:
           application/json:
             schema:
               type: object
               properties:
                 data:
                   type: object
                   properties:
                     enabled:
                       type: string
                       example: "1"
```

Security fuzzer:

```yaml
/example/endpoint:
   test_1:
     description: Fuzz endpoint
     data#enabled: "1"
     expectedResponseCode: 422
     httpMethod: all
     targetFieldTypes:
       - string
     stringsFile: file_2.txt
```

As a comparison between two versions of CATS, below are values being sent with the same API specification and Security fuzzer files:
**Version 9.0.0**
![image](https://github.com/Endava/cats/assets/32774768/b8abd125-cbe6-42d9-8c08-d7f307ff288d)

**Version 8.4.0**
![image](https://github.com/Endava/cats/assets/32774768/cb58d75f-2434-4d7d-9981-f48c2512f49c)

Has parsing changed in v9.0.0, or is this a new bug?

Thank you!
