### ISSUE TITLE
[Functional Fuzzer] Requesting Ability to Set Parameter Values as NULL for POST Requests in CATs

### ISSUE THREAD

**Issue by beam-me-up** [Endava/cats#80]
In my CATs test scenarios, I've noticed a behavior related to setting values as "null." While I can use the "cats_remove_field" flag to remove parameters for GET requests, I'm facing a situation with POST requests where I want to set a parameter's value as NULL without removing it entirely.

Examples:

For instance, consider the following YAML examples:

```yml
/pet/findByStatus:
    test_2:
      description: Get to status
      httpMethod: GET
      status: null 
      expectedResponseCode: 200
```
In this case, I can use "cats_remove_field" for GET requests to remove the "status" parameter completely.

However, for POST requests like this:

```yml
/pet:
    test_1:
      description: Create a Pet
      httpMethod: POST
      name: null
      expectedResponseCode: 200
```
I don't want to remove the "name" parameter, but I need to set its value as NULL.

Question:

Is there a way to set the value of a parameter as NULL explicitly for POST requests in CATs, without removing the parameter itself?

Any guidance or solution for this situation would be greatly appreciated.
