### ISSUE TITLE
[Functional Fuzzer] Date String Parsing Bug

### ISSUE THREAD

**Issue by beam-me-up** [Endava/cats#83]
In my CATs test scenarios, I've observed an issue related to parsing date values. When I set a date value like '2023-03-03', the system interprets it as a mathematical expression and converts it to '2017'.

For instance, consider the following YAML examples:
```yml
/pet/findByStatus:
    test_2:
      description: Get to status
      httpMethod: GET
      status: cats
      expectedResponseCode: 200
      createdAt: '2023-03-03'
```
This corresponds to the 'createdAt' parameter in the OpenAPI specification:
```yml
- name: createdAt
  in: query
  description: Some random date
  schema:
    type: string
```

Expected behavior: The system should treat date strings like '2023-03-03' as plain strings and not perform any mathematical operations on them.

I've attached the OpenAPI YAML file for reference. Please let me know if you need any further details or clarification.
